export const FETCH_ADD_TO_CART = 'FETCH_ADD_TO_CART';
export const FETCH_REMOVE_FROM_CART = 'FETCH_REMOVE_FROM_CART';
export const FETCH_CLEAR_CART = 'FETCH_CLEAR_CART';

export const FETCH_CHANGE_QUANTITY = 'FETCH_CHANGE_QUANTITY';