export const FETCH_CREATE_PRODUCT = 'FETCH_CREATE_PRODUCT';
export const SUCCESS_FETCH_CREATE_PRODUCT = 'SUCCESS_FETCH_CREATE_PRODUCT';
export const FAILURE_FETCH_CREATE_PRODUCT = 'FAILURE_FETCH_CREATE_PRODUCT';

export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const SUCCESS_FETCH_PRODUCTS_LIST = 'SUCCESS_FETCH_PRODUCTS_LIST';
export const FETCH_COMPANY_PRODUCTS_LIST = 'FETCH_COMPANY_PRODUCTS_LIST';
export const SUCCESS_FETCH_COMPANY_PRODUCTS_LIST = 'SUCCESS_FETCH_COMPANY_PRODUCTS_LIST';

export const FAILURE_FETCH_PRODUCTS_LIST = 'FAILURE_FETCH_PRODUCTS_LIST';

export const FETCH_PRODUCT_ITEM = 'FETCH_PRODUCT_ITEM';
export const SUCCESS_FETCH_PRODUCT_ITEM = 'SUCCESS_FETCH_PRODUCT_ITEM';
export const FAILURE_FETCH_PRODUCT_ITEM = 'FAILURE_FETCH_PRODUCT_ITEM';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const SUCCESS_UPLOAD_IMAGE = 'SUCCESS_UPLOAD_IMAGE';

export const DISMISS_PRODUCT_MESSAGE = 'DISMISS_PRODUCT_MESSAGE';

export const EDIT_PRODUCT_ITEM = 'EDIT_PRODUCT_ITEM';
export const SUCCESS_EDIT_PRODUCT_ITEM = 'SUCCESS_EDIT_PRODUCT_ITEM';

