export const FETCH_SIGN_IN = 'FETCH_SIGN_IN';
export const SUCCESS_FETCH_SIGN_IN = 'SUCCESS_FETCH_SIGN_IN';
export const FAILURE_FETCH_SIGN_IN = 'FAILURE_FETCH_SIGN_IN';
export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const SUCCESS_FETCH_PROFILE = 'SUCCESS_FETCH_PROFILE';
export const FAILURE_FETCH_PROFILE = 'FAILURE_FETCH_PROFILE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SUCCESS_UPDATE_PROFILE = 'SUCCESS_UPDATE_PROFILE';

export const SIGN_OUT = 'SIGN_OUT';