# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('created_on', models.DateField(verbose_name='Дата производства')),
                ('expires_on', models.DateField(verbose_name='Срок хранения')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product', verbose_name='Товар')),
            ],
        ),
    ]
