# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость доставки')),
                ('total_price', models.PositiveIntegerField(verbose_name='Итого')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shipment_method', models.CharField(blank=True, choices=[('courier', 'Курьер'), ('pick-up', 'Забрать с магазина')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказы')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за единицу товара')),
                ('total_price', models.PositiveIntegerField(verbose_name='Общая цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Order', verbose_name='Товары')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.Product', verbose_name='Товар'),
        ),
    ]
