# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170616_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Мыломойка'), (2, 'Хоз товары')], default=0, verbose_name='Категория'),
        ),
    ]
