# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('processed', 'Подтвержден'), ('shipped', 'Отправлен'), ('picked-up', 'Получил'), ('complete', 'Выполнен'), ('canceled', 'Отменен')], default='processing', max_length=255),
        ),
    ]
