# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170620_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('storehouse', 'Склад'), ('store', 'Торговая точка')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Подтвержден'), ('denied', 'Отклонен')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userrolerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
