# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('storehouse', 'Компания'), ('store', 'Торговая точка')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrolerequest',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('storehouse', 'Компания'), ('store', 'Торговая точка')], max_length=50),
        ),
    ]
