# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 05:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filtered_cities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
