export const FETCH_ORDERS = 'FETCH_ORDERS';
export const SUCCESS_FETCH_ORDERS = 'SUCCESS_FETCH_ORDERS';
export const FAILURE_FETCH_ORDERS = 'FAILURE_FETCH_ORDERS';

export const FETCH_ORDER_PRODUCTS = 'FETCH_ORDER_PRODUCTS';
export const SUCCESS_FETCH_ORDER_PRODUCTS = 'SUCCESS_FETCH_ORDER_PRODUCTS';
export const FAILURE_FETCH_ORDER_PRODUCTS = 'FAILURE_FETCH_ORDER_PRODUCTS';
